name: pytorch-CycleGAN-and-pix2pix
channels:
- pytorch
- defaults
dependencies:
- python=3.8
- pytorch
- scipy
- torchvision
- pip
- dominate
- wandb
- visdom
- pip:
  - Pillow==8.0.1
  - numpy==1.19.2